import test from 'node:test';import assert from 'node:assert/strict';import {readFile} from 'node:fs/promises';import {parseStatement,makeRequest} from './categorizer.mjs';
test('real statement preserves signed money and dates and omits account fields',async()=>{const rows=parseStatement(await readFile('Lista_operacji_20260927_152250.txt','utf8'));assert.equal(rows.length,339);assert.equal(rows[0].amount,-100.74);assert.equal(rows[0].date,'2026-09-26');assert.equal(rows[0].currency,'PLN');assert.ok(!JSON.stringify(rows).includes('5247'));const req=makeRequest(rows.slice(0,2));assert.equal(Object.keys(req.questions).length,2);assert.ok(req.questions.t1.instructions.includes('transactions[1]'));assert.ok(!JSON.stringify(req).includes('5247'));});
test('reject unsupported and malformed inputs',()=>{assert.throws(()=>parseStatement('hello'),/No transactions/);assert.throws(()=>parseStatement('01.09.2026\t01.09.2026\tShop\t\t\t\tbad\tPLN\tref\tZAKUP'),/could not be read/)});
test('parse incoming and decimal comma with thousand spaces',()=>{const [t]=parseStatement('01.09.2026\t01.09.2026\tShop\t\t\tRefund\t1 200,50\tPLN\tref\tREFUND');assert.equal(t.amount,1200.5)});
import {parseBank,reconcile,parseCSV} from './bank.mjs';
test('bank CSV matches statement one to one without changing totals',async()=>{const a=parseStatement(await readFile('Lista_operacji_20260927_152250.txt','utf8'));const b=parseBank(await readFile('Lista_operaci_20260927_153225.csv'.replace('operaci','operacji'),'utf8'));const matched=reconcile(a,b);assert.equal(b.length,350);assert.equal(matched.filter(t=>t.bankCategory).length,339);assert.equal(matched[0].bankCategory,'Lekarstwa');assert.equal(matched.reduce((s,t)=>s+t.amount,0),a.reduce((s,t)=>s+t.amount,0));});
test('CSV parser handles quoted delimiters and duplicate matching safely',()=>{assert.deepEqual(parseCSV('a;b\n"x;y";"z"'),[['a','b'],['x;y','z']]);const t={date:'2026-09-01',merchant:'shop',amount:-1,currency:'PLN',title:''};const result=reconcile([t,t],[{...t,bankCategory:'Groceries'}]);assert.equal(result.filter(t=>t.bankCategory).length,1)});
import {reviewedDecision} from './reviewed.mjs';
test('merchant evidence corrects misleading bank categories without inventing confidence',()=>{assert.equal(reviewedDecision({merchant:'Mol*vintrica 123 DE'}).category,'transport');assert.equal(reviewedDecision({merchant:'siepomaga.pl Poznan PL'}).category,'giving');assert.equal(reviewedDecision({merchant:'PeP*ZONA KRAWCA - CUKI'}).category,'dining');assert.equal(reviewedDecision({merchant:'siepomaga.pl'}).confidence,undefined);assert.deepEqual(reviewedDecision({merchant:'unknown'}),{})});
